Repository Purple-Print/network-server, pull requests merged in 2022-11, with the labels that each got.

#25 회원 도메인 - #19 회원가입, #20 로그인 기능 구현
  .gitignore
  pom.xml
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/controller/AuthController.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/ChildDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/EmailDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/LoginDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/SignUpDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/TokenDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/UserDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/exception/LoginFailedException.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/AuthService.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/MailService.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/model/Child.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/model/User.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/model/UserRole.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/repository/ChildRepository.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/repository/UserRepository.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/query/controller/AuthController.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/query/dto/UsernameDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/query/service/AuthService.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/AsyncConfig.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/JwtSecurityConfig.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/SecurityConfig.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/customuser/CustomUserDetailsService.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/dto/ApiExceptionDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/dto/ChildDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/dto/UserDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/TokenException.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/ValidExceptionHandler.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/responsemessage/ResponseMessage.java
  src/main/java/com/purpleprint/network/purpleprintproject/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/purpleprint/network/purpleprintproject/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/purpleprint/network/purpleprintproject/jwt/JwtFilter.java
  src/main/java/com/purpleprint/network/purpleprintproject/jwt/TokenProvider.java
  src/main/resources/application.yml
Labels: ✨New Feature, ⚙️Settings

#27 #21 spring security 권한 설정 수정
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/AuthService.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/model/UserRole.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/SecurityConfig.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/customuser/CustomUserDetailsService.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/dto/UserDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/jwt/TokenProvider.java
Labels: 💥Bug Fix

#28 Entity/hak
  .gitignore
  src/test/java/com/purpleprint/network/purpleprintproject/PurpleprintEntityTests.java
  src/test/java/com/purpleprint/network/purpleprintproject/RoleType.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/AbnormalBehavior.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Analysis.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Character.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Characterfile.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Child.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Heart.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Log.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Login.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Logout.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Post.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/User.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Video.java
Labels: ✅Test

#29 회원 도메인 - #26 아이디, 비밀번호 찾기 API
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/controller/AuthController.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/MatchPasswordDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/MatchUsernameDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/AuthService.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/MailService.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/repository/UserRepository.java
Labels: ✨New Feature

#30 회원 도메인 로그인, 회원가입, 아이디 찾기, 비밀번호 찾기 / Entity TEST 코드
  .gitignore
  pom.xml
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/controller/AuthController.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/ChildDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/EmailDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/LoginDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/MatchPasswordDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/MatchUsernameDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/SignUpDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/TokenDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/UserDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/exception/LoginFailedException.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/AuthService.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/MailService.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/model/Child.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/model/User.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/model/UserRole.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/repository/ChildRepository.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/repository/UserRepository.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/query/controller/AuthController.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/query/dto/UsernameDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/query/service/AuthService.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/AsyncConfig.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/JwtSecurityConfig.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/SecurityConfig.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/customuser/CustomUserDetailsService.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/dto/ApiExceptionDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/dto/ChildDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/dto/UserDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/TokenException.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/ValidExceptionHandler.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/responsemessage/ResponseMessage.java
  src/main/java/com/purpleprint/network/purpleprintproject/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/purpleprint/network/purpleprintproject/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/purpleprint/network/purpleprintproject/jwt/JwtFilter.java
  src/main/java/com/purpleprint/network/purpleprintproject/jwt/TokenProvider.java
  src/main/resources/application.yml
  src/test/java/com/purpleprint/network/purpleprintproject/PurpleprintEntityTests.java
  src/test/java/com/purpleprint/network/purpleprintproject/RoleType.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/AbnormalBehavior.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Analysis.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Character.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Characterfile.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Child.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Heart.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Log.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Login.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Logout.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Post.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/User.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Video.java
Labels: 💥Bug Fix, ✨New Feature, ⚙️Settings, ✅Test

#32 회원 도메인 - 자녀 계정 생성 api 구현
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/controller/UserController.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/ChildDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/exception/ChildAccountCreationFailException.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/UserService.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/model/Child.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/repository/ChildRepository.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/CommonExceptionHandler.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/ValidExceptionHandler.java
Labels: 💥Bug Fix, ✨New Feature

#35 회원 도메인 - #21 로그인 api 수정, #33 회원 탈퇴 api
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/controller/UserController.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/exception/DeleteUserFailException.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/AuthService.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/UserService.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/repository/UserRepository.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/CommonExceptionHandler.java
Labels: 💥Bug Fix, ✨New Feature

#40 회원 도메인 - #37 비밀번호 수정 api 구현
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/controller/UserController.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/PasswordDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/exception/UpdatePasswordFailException.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/UserService.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/CommonExceptionHandler.java
Labels: ✨New Feature

#47 #45 Heart 도메인 - api 버그 수정
  src/main/java/com/purpleprint/network/purpleprintproject/heart/command/application/controller/HeartController.java
  src/main/java/com/purpleprint/network/purpleprintproject/heart/command/application/dto/HeartDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/heart/command/application/service/HeartService.java
  src/main/java/com/purpleprint/network/purpleprintproject/heart/command/domain/repository/HeartRepository.java
Labels: ✨New Feature

#48 Heart 도메인 - #46 날짜 별 heart 보유 정보, 나눔 정보 초기화 추가
  src/main/java/com/purpleprint/network/purpleprintproject/PurpleprintProjectApplication.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/UserService.java
  src/main/java/com/purpleprint/network/purpleprintproject/heart/command/application/service/HeartService.java
  src/main/java/com/purpleprint/network/purpleprintproject/heart/command/domain/service/ChildHeartService.java
  src/main/java/com/purpleprint/network/purpleprintproject/heart/command/infra/service/ChildHeartServiceImpl.java
Labels: ✨New Feature

#50 #38 s3 스토리지 업로드 구현
  pom.xml
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/AwsConfig.java
  src/main/java/com/purpleprint/network/purpleprintproject/s3/dto/FileDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/s3/exception/FileEmptyException.java
  src/main/java/com/purpleprint/network/purpleprintproject/s3/service/AwsS3UploadService.java
  src/main/resources/application.yml
Labels: ✨New Feature

#52 s3 스토리지 - #51 비동기 처리 업로드
  src/main/java/com/purpleprint/network/purpleprintproject/s3/repository/AwsS3UploadRepository.java
  src/main/java/com/purpleprint/network/purpleprintproject/s3/service/AwsS3UploadService.java
Labels: 💥Bug Fix, ✨New Feature

#57 캐릭터 도메인 - #42 캐릭터 생성 api 구축
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/ChildInfoDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/UserService.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/controller/CharacterController.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/dto/CharacterDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/exception/CreateCharacterFailException.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/service/CharacterService.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/domain/model/Character.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/domain/model/CharacterFile.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/domain/respository/CharacterFileRepository.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/CommonExceptionHandler.java
Labels: 💥Bug Fix, ✨New Feature

#58 놀이 도메인 - #44 영상 조회 , #54 영상 저장, #56 영상 삭제 구현
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/CommonExceptionHandler.java
  src/main/java/com/purpleprint/network/purpleprintproject/play/command/application/controller/PlayController.java
  src/main/java/com/purpleprint/network/purpleprintproject/play/command/application/dto/VideoDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/play/command/application/exception/DeleteVideoFailedException.java
  src/main/java/com/purpleprint/network/purpleprintproject/play/command/application/exception/SaveVideoFailedException.java
  src/main/java/com/purpleprint/network/purpleprintproject/play/command/application/service/PlayService.java
  src/main/java/com/purpleprint/network/purpleprintproject/play/command/domain/model/Video.java
  src/main/java/com/purpleprint/network/purpleprintproject/play/command/domain/repository/VideoRepository.java
Labels: 💥Bug Fix, ✨New Feature

#64 회원 도메인 - #60 로그아웃 사용자 행동 분석 api 호출 일부 구현 & #59 자녀 계정 접속 수정 & #63 swagger 생성
  pom.xml
  src/main/java/com/purpleprint/network/purpleprintproject/PurpleprintProjectApplication.java
  src/main/java/com/purpleprint/network/purpleprintproject/analysis/command/application/service/AnalysisService.java
  src/main/java/com/purpleprint/network/purpleprintproject/analysis/command/domain/service/BehavioralAnalysisService.java
  src/main/java/com/purpleprint/network/purpleprintproject/analysis/command/infra/service/BehavioralAnalysisServiceImpl.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/ChildInfoDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/SignUpDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/UserService.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/SecurityConfig.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: 💥Bug Fix, ✨New Feature

#65 캐릭터 도메인 - #41 캐릭터 생성을 위한 외부 서버와의 파일 주고받기 진행 중
  pom.xml
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/controller/CharacterController.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/dto/PictureDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/exception/PictureReceiveFailException.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/service/CharacterService.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/domain/service/RecommendService.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/infra/service/RecommendServiceImpl.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/CommonExceptionHandler.java
Labels: ✨New Feature

#67 게시 도메인 - #44 게시된 영상 조회 api, #55 게시 영상 신청 api, #66 게시 신청 내역 조회 api
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/CommonExceptionHandler.java
  src/main/java/com/purpleprint/network/purpleprintproject/play/command/application/controller/PlayController.java
  src/main/java/com/purpleprint/network/purpleprintproject/play/command/application/service/PlayService.java
  src/main/java/com/purpleprint/network/purpleprintproject/play/query/service/PlayService.java
  src/main/java/com/purpleprint/network/purpleprintproject/post/command/application/controller/PostController.java
  src/main/java/com/purpleprint/network/purpleprintproject/post/command/application/dto/PostDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/post/command/application/exception/SavePostAndVideoFailException.java
  src/main/java/com/purpleprint/network/purpleprintproject/post/command/application/service/PostService.java
  src/main/java/com/purpleprint/network/purpleprintproject/post/command/domain/model/Post.java
  src/main/java/com/purpleprint/network/purpleprintproject/post/command/domain/repository/PostRepository.java
  src/main/java/com/purpleprint/network/purpleprintproject/post/command/domain/service/PostingVideoService.java
  src/main/java/com/purpleprint/network/purpleprintproject/post/command/infra/service/PostingVideoServiceImpl.java
Labels: 💥Bug Fix, ✨New Feature

#73 캐릭터 도메인 - #41 캐릭터 추천 api 구현
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/controller/CharacterController.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/service/CharacterService.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/domain/service/RecommendService.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/infra/service/RecommendServiceImpl.java
Labels: ✨New Feature

#76 캐릭터, 하트 도메인 - #41, #75 캐릭터 컨트롤러 수정, 하트 나눔 랭킹 조회 기능 추가
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/model/Child.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/repository/ChildRepository.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/controller/CharacterController.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/dto/ResponseDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/heart/command/application/controller/HeartController.java
  src/main/java/com/purpleprint/network/purpleprintproject/heart/command/application/dto/RankingDTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/heart/command/application/service/HeartService.java
Labels: ✨New Feature

#78 GitHub actions - #77 CI를 위한 환경 구축
  .github/workflows/purpleprint.yml
Labels: 🎈Deployment

#81 fix : #23 테스트 코드 삭제
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/model/Child.java
  src/test/java/com/purpleprint/network/purpleprintproject/PurpleprintEntityTests.java
  src/test/java/com/purpleprint/network/purpleprintproject/PurpleprintProjectApplicationTests.java
  src/test/java/com/purpleprint/network/purpleprintproject/RoleType.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/AbnormalBehavior.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Analysis.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Character.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Characterfile.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Child.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Heart.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Log.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Login.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Logout.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Post.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/User.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Video.java
Labels: 💥Bug Fix

#82 fix : #23 테스트 코드 삭제
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/model/Child.java
  src/test/java/com/purpleprint/network/purpleprintproject/PurpleprintEntityTests.java
  src/test/java/com/purpleprint/network/purpleprintproject/PurpleprintProjectApplicationTests.java
  src/test/java/com/purpleprint/network/purpleprintproject/RoleType.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/AbnormalBehavior.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Analysis.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Character.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Characterfile.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Child.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Heart.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Log.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Login.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Logout.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Post.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/User.java
  src/test/java/com/purpleprint/network/purpleprintproject/entities/Video.java
Labels: 💥Bug Fix

#83 #80 config server 생성
  pom.xml
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: ⚙️Settings

#84 deployment : #77 github actions 웹 이미지 빌드 및 도커허브에 push 코드 추가
  .github/workflows/purpleprint.yml
Labels: 🎈Deployment

#87 #86 docker file pull request
  Dockerfile
  pom.xml
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: 🎈Deployment

#85 GitHub actions - #77 Get Current Time id 변경
  .github/workflows/purpleprint.yml
Labels: 🎈Deployment

#88 deployment : #86 dockerfile 생성
  Dockerfile
Labels: 🎈Deployment

#91 swagger AuthenticationPrincipal 파라미터 제거
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/SwaggerConfig.java
Labels: ⚙️Settings

#92 Dev -> Main #90 swagger AuthenticationPrincipal 파라미터 제거
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/SwaggerConfig.java
Labels: ⚙️Settings

#93 setting : #90 swagger base package 설정
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/SwaggerConfig.java
Labels: ⚙️Settings

#94 dev -> main : setting : #90 swagger base package 설정
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/SwaggerConfig.java
Labels: 🎈Deployment, ⚙️Settings

#96 setting : config 서버 중지로 주소 변경
  src/main/resources/application.yml
Labels: 💥Bug Fix

#97 Dev -> main pull request
  src/main/resources/application.yml
Labels: 💥Bug Fix

#99 fix : #98 x,y,z, 좌표 null point exception 문제 해결 pull request 입니다.
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/UserService.java
Labels: 💥Bug Fix

#100 Dev -> main #98 오류 해결
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/UserService.java
Labels: 💥Bug Fix

#101 Character 도메인 - return type value 수정
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/controller/CharacterController.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/service/CharacterService.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/domain/service/RecommendService.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/infra/service/RecommendServiceImpl.java
Labels: 💥Bug Fix

#102 character 도메인 - #41 return value 수정
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/controller/CharacterController.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/service/CharacterService.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/domain/service/RecommendService.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/infra/service/RecommendServiceImpl.java
Labels: 💥Bug Fix

#104 캐릭터 도메인 - #103 캐릭터 추천 exception 처리 및 ai 서버 수정 pull request 입니다
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/exception/RecommendCharacterFailException.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/infra/service/RecommendServiceImpl.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/CommonExceptionHandler.java
Labels: 💥Bug Fix, ✨New Feature

#105 Dev -> main #103 캐릭터 추천 exception 처리 및 ai 서버 수정
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/exception/RecommendCharacterFailException.java
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/infra/service/RecommendServiceImpl.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/exception/CommonExceptionHandler.java
Labels: 💥Bug Fix, ✨New Feature

#106 fix: #103 캐릭터 추천 swagger 작동 문제 해결 pull request
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/controller/CharacterController.java
Labels: 💥Bug Fix

#107 Dev -> main #103 캐릭터 추천 swagger 연동 문제 해결
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/controller/CharacterController.java
Labels: 💥Bug Fix

#110 Dev -> main 회원 도메인 : #108 로그아웃 v2 api 구현 pull requets입니다.
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/controller/AuthController.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/dto/LogoutV2DTO.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/application/service/AuthService.java
Labels: ✨New Feature

#111 fix: #108 log int -> long 변경
  src/main/java/com/purpleprint/network/purpleprintproject/analysis/command/application/dto/LogDTO.java
Labels: 💥Bug Fix

#112 Dev -> main log dto 수정
  src/main/java/com/purpleprint/network/purpleprintproject/analysis/command/application/dto/LogDTO.java
Labels: 💥Bug Fix

#113 fix: #41 ai 서버 변경
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/infra/service/RecommendServiceImpl.java
Labels: 💥Bug Fix

#114 Dev -> main #41 ai 서버 변경
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/infra/service/RecommendServiceImpl.java
Labels: 💥Bug Fix

#115 로그아웃api 이상 행동 제거
  src/main/java/com/purpleprint/network/purpleprintproject/analysis/command/application/service/AnalysisService.java
Labels: 💥Bug Fix

#116 Dev -> main 이상행동 제거
  src/main/java/com/purpleprint/network/purpleprintproject/analysis/command/application/service/AnalysisService.java
Labels: 💥Bug Fix

#118 feature && fix: #117 캐릭터 존재 시 update
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/service/CharacterService.java
Labels: 💥Bug Fix, ✨New Feature

#119 Dev -> main feature && fix: #117 캐릭터 존재 시 update
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/service/CharacterService.java
Labels: 💥Bug Fix, ✨New Feature

#120 Dev -> main Dockerrun.aws.json upload
  Dockerrun.aws.json
Labels: 📃Docs

#122 Dev ->main : feature : #121 elastic beanstalk health 체크를 위한 api 생성 pull request
  src/main/java/com/purpleprint/network/purpleprintproject/common/config/SecurityConfig.java
  src/main/java/com/purpleprint/network/purpleprintproject/common/controller/CommomController.java
Labels: 🎈Deployment, ✨New Feature

#125 Dev -> main : bug fix : 하트 랭킹 sort 변경
  src/main/java/com/purpleprint/network/purpleprintproject/PurpleprintProjectApplication.java
  src/main/java/com/purpleprint/network/purpleprintproject/auth/command/domain/model/Child.java
Labels: 💥Bug Fix

#126 readme update
  README.md
Labels: 📃Docs

#127 readme update
  README.md
Labels: 📃Docs

#129 Readme file Stacks 추가
  README.md
Labels: 📃Docs

#130 Readme file git branch strategy 추가
  README.md
Labels: 📃Docs

#132 fix && feature : #131 캐릭터 추천 사용자 이미지 예외처리 추가
  .ebextensions/nginx/conf.d/myconf.conf
  README.md
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/controller/CharacterController.java
Labels: 💥Bug Fix

#133 Dev -> main #131 캐릭터 추천 사용자 얼굴 이미지 확장자 예외처리
  src/main/java/com/purpleprint/network/purpleprintproject/character/command/application/controller/CharacterController.java
Labels: 💥Bug Fix
